### ISSUE TITLE
getting error, advice commands to install on ubuntu

### ISSUE THREAD

**Issue by creativewebmall** [p-ho/emailIdx#4] opened 2015-07-20 12:59 UTC
(EIDX_ENV)creative9@creative9-desktop ~/Downloads/emailIdx-master/emailidx $ emailidx
Traceback (most recent call last):
  File "/home/creative9/Downloads/emailIdx-master/EIDX_ENV/bin/emailidx", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 3018, in <module>
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 612, in _build_master
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 918, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/**init**.py", line 805, in resolve
pkg_resources.DistributionNotFound: M2Crypto

**Comment by p-ho** [comment] 2015-07-20 21:18
Is M2Crypto properly installed?
You may check by issuing:

```
(EIDX_ENV)$ pip freeze
```

**Comment by creativewebmall** [comment] 2015-07-21 03:42
Hi,

I tried installing M2Crypto using other methods and one of the methods
(pip) worked.  I guess installing it through easy_install gives error.

Thank you for the quick advice.

Warm Regards,

Sony Surana
Creative Web Mall (I) Pvt. Ltd.
http://www.creativewebmall.com/

**Comment by p-ho** [comment] 2015-07-21 10:15
You're welcome.
One additional question: Have you used the `$ python setup.py install` - approach for installing?
 M2Crypto should be installed as a dependency automatically.

**Comment by creativewebmall** [comment] 2015-07-21 10:54
We first tried to run the installtion commands as mentioned on this page.
https://github.com/p-ho/emailIdx

When all failed then we checked on internet and found other url
https://pypi.python.org/pypi/M2Crypto
from which we downloaded the file and then used the
command: $ python setup.py install

Warm Regards,

Sony Surana
CREATIVE WEB MALL (INDIA) PVT LTD.
URL: *http://www.creativewebmall.com/ http://www.creativewebmall.com/  *

**Comment by p-ho** [comment] 2015-07-21 11:08
Ok. I made a quick try to reproduce your issue on my openSUSE-machine. But I wasn't able to.
As soon as I can find the time to I'll be checking it on Ubuntu although I can hardly find a logical reason for the behavior you've described.

**Comment by p-ho** [comment] 2015-08-17 02:46
I couldn't reproduce that behavior on Ubuntu either.
So I'll close the issue for now.

**Closed as completed by p-ho** 2015-08-17 02:46 UTC
